### PR TITLE
Enable tinder social

### PR DESCRIPTION
**Pull request by yanirz**

### CODE REVIEW

**Comment by adrianmcli** [comment]
Is it necessary to log the entire response from the post request into the console?

**Comment by yanirz** [comment]
Followed the _get convention that also prints it. @adrianmc

**Comment by jkfran** [comment]
That's ok!! but still no friends for me... They need to activate tinder social too?

**Comment by defaultnamehere** [comment]
This is good, but I'd like it to include a prompt that says "HEY IS IT OKAY IF I ENABLE TINDER SOCIAL ON YOUR ACCOUNT ALL YOUR FRIENDS WILL BE ABLE TO SEE YOU ON TINDER LOL" or similar

**Comment by RobertPaulson90** [comment]
Tried your new code but still {"status":200,"results":[]} sadly

**Pull request closed without merging**
